//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ilahiyyat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisement
    {
        public int id { get; set; }
        public string elanin_adi { get; set; }
        public string elanin_şəkili { get; set; }
        public string elanin_məzmunu { get; set; }
        public Nullable<System.DateTime> elanin_başlanqic_günü { get; set; }
        public Nullable<System.DateTime> elanin_bitdiyi_gün { get; set; }
        public string elanin_yeri { get; set; }
        public string elanin_təşkilaçinin_adi { get; set; }
        public string elanin_təşkilaçinin_nomrəsi { get; set; }
        public string elanin_təşkilaçinin_email { get; set; }
    }
}
