//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ilahiyyat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int id { get; set; }
        public string xəberin_adi { get; set; }
        public string xəberin_məzmunu { get; set; }
        public Nullable<System.DateTime> xəberin_əlavə_edilən_gün { get; set; }
        public Nullable<int> xəberin_baxiş_sayi { get; set; }
        public string xəberin_şəkili { get; set; }
    }
}
