//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ilahiyyat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int id { get; set; }
        public string sual { get; set; }
        public string cavab { get; set; }
        public string sual_user_adi { get; set; }
        public string sual_user_email { get; set; }
        public string sual_əlavə_edilən_gün { get; set; }
        public Nullable<int> sual_baxiş_sayi { get; set; }
    }
}
