//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ilahiyyat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sermon
    {
        public int id { get; set; }
        public string xutbə_adi { get; set; }
        public string xutbə_məzmunu { get; set; }
        public string xutbə_audio { get; set; }
    }
}
